### PR TITLE
Feature/improve type exports

### PR DESCRIPTION
**Pull request by PierreJeanjacquot**
- improve types exports
- fix supported `targetBlockchains`

### CODE REVIEW

**Review by Le-Caignec — CHANGES_REQUESTED** [review]
I think it could be nice to follow the same pattern as DPS for **builder** and us.
- file names are written using CamelCase
- instead of `public-types.ts`, we named it` index.ts`

**Comment by PierreJeanjacquot** [comment]
> I think it could be nice to follow the same pattern as DPS for **builder** and us.

to be clear, builders don't import the internal modules, if we decide to adopt this convention it only impacts the development team.

**Comment by PierreJeanjacquot** [comment]
@Le-Caignec
- applied file name suggestions
- removed Mumbai which was still an available target blockchain but is not working anymore

**Review by Le-Caignec — APPROVED** [review]
LGTM

**Pull request merged**
